#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.9
# from Racc grammer file "".
#

require 'racc/parser.rb'
module Css
  class Parser < Racc::Parser

module_eval(<<'...end css.racc/module_eval...', 'css.racc', 38)

def parse tokens
  @tokens = tokens
  do_parse
end

def next_token
  @tokens.shift
end
...end css.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
    16,     6,     6,     8,    11,    14,    15,     7,    11,     6,
    20,     6,     6 ]

racc_action_check = [
     8,     8,     0,     3,     4,     5,     7,     1,     9,    10,
    14,    16,    18 ]

racc_action_pointer = [
    -2,     7,   nil,     1,     1,     0,   nil,     6,    -3,     5,
     5,   nil,   nil,   nil,     6,   nil,     7,   nil,     8,   nil,
   nil,   nil,   nil ]

racc_action_default = [
   -15,   -15,    -1,    -2,    -5,    -9,   -11,   -15,   -15,    -6,
   -15,   -14,   -10,   -12,   -15,    23,   -15,    -4,   -15,    -7,
   -13,    -3,    -8 ]

racc_goto_table = [
     2,    19,    10,     9,     1,    12,    13,    18,    17,    22,
   nil,   nil,   nil,   nil,   nil,   nil,    21 ]

racc_goto_check = [
     2,     4,     6,     5,     1,     8,     9,     6,     2,     4,
   nil,   nil,   nil,   nil,   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,     4,     0,   nil,    -9,    -1,    -2,   nil,     0,     1 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,   nil,   nil,     5,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 7, :_reduce_none,
  1, 8, :_reduce_2,
  4, 8, :_reduce_3,
  3, 8, :_reduce_4,
  1, 9, :_reduce_5,
  2, 9, :_reduce_6,
  2, 11, :_reduce_7,
  3, 11, :_reduce_8,
  1, 10, :_reduce_9,
  2, 10, :_reduce_10,
  1, 13, :_reduce_11,
  1, 14, :_reduce_12,
  2, 15, :_reduce_13,
  1, 12, :_reduce_14 ]

racc_reduce_n = 15

racc_shift_n = 23

racc_token_table = {
  false => 0,
  :error => 1,
  :COMMA => 2,
  :S => 3,
  :name => 4,
  "." => 5 }

racc_nt_base = 6

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "COMMA",
  "S",
  "name",
  "\".\"",
  "$start",
  "start",
  "selectors_group",
  "selector",
  "simple_selector_sequence",
  "annoying_bit",
  "combinator",
  "element_name",
  "modifier",
  "class" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

module_eval(<<'.,.,', 'css.racc', 7)
  def _reduce_2(val, _values, result)
     result = [:selectors_group, *val] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 8)
  def _reduce_3(val, _values, result)
     result = [:selectors_group, *val] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 9)
  def _reduce_4(val, _values, result)
     result = [:selectors_group, *val] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 12)
  def _reduce_5(val, _values, result)
     result = [:selector, *val] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 13)
  def _reduce_6(val, _values, result)
    first, *rest = *val; rest.flatten!(1); result =  [:selector, first, *rest] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 16)
  def _reduce_7(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 17)
  def _reduce_8(val, _values, result)
     previous_combinators = val.shift; result = previous_combinators + val 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 20)
  def _reduce_9(val, _values, result)
     result = [:simple_selector_sequence, *val] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 21)
  def _reduce_10(val, _values, result)
     first, *rest = *val; rest.flatten(1); result = [:simple_selector_sequence, first, *rest ]  
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 24)
  def _reduce_11(val, _values, result)
     result = [:element_name, *val] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 27)
  def _reduce_12(val, _values, result)
     result = [:class, val.flatten(1)] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 30)
  def _reduce_13(val, _values, result)
    result = [:name, val.last] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 33)
  def _reduce_14(val, _values, result)
     result = [:combinator, *val] 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Css
