#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.9
# from Racc grammer file "".
#

require 'racc/parser.rb'
module Css
  class Parser < Racc::Parser

module_eval(<<'...end css.racc/module_eval...', 'css.racc', 39)

def parse tokens
  @tokens = tokens
  do_parse
end

def next_token
  @tokens.shift
end
...end css.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
    18,     7,     9,     7,     9,     7,     9,     7,     9,     7,
     9,    16,     9,    14,    14,    11,    10,    17 ]

racc_action_check = [
    11,    11,    11,    13,    13,    18,    18,     0,     0,    20,
    20,     9,     5,     4,    12,     3,     1,    10 ]

racc_action_pointer = [
     3,    16,   nil,    13,    10,     7,   nil,   nil,   nil,     7,
    17,    -3,    11,    -1,   nil,   nil,   nil,   nil,     1,   nil,
     5,   nil,   nil,   nil ]

racc_action_default = [
   -16,   -16,    -1,    -2,    -5,    -9,   -11,   -12,   -13,   -16,
   -16,   -16,    -6,   -16,   -15,   -10,   -14,    24,   -16,    -4,
   -16,    -7,    -3,    -8 ]

racc_goto_table = [
     2,    13,    12,    21,     1,    15,   nil,   nil,   nil,    20,
    23,    19,   nil,   nil,   nil,   nil,   nil,   nil,    22 ]

racc_goto_check = [
     2,     6,     5,     4,     1,     8,   nil,   nil,   nil,     6,
     4,     2,   nil,   nil,   nil,   nil,   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,     4,     0,   nil,   -10,    -2,    -3,   nil,     0,   nil ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,   nil,   nil,     5,     6,     8 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 7, :_reduce_none,
  1, 8, :_reduce_2,
  4, 8, :_reduce_3,
  3, 8, :_reduce_4,
  1, 9, :_reduce_5,
  2, 9, :_reduce_6,
  2, 11, :_reduce_7,
  3, 11, :_reduce_8,
  1, 10, :_reduce_9,
  2, 10, :_reduce_10,
  1, 10, :_reduce_11,
  1, 13, :_reduce_12,
  1, 14, :_reduce_13,
  2, 15, :_reduce_14,
  1, 12, :_reduce_15 ]

racc_reduce_n = 16

racc_shift_n = 24

racc_token_table = {
  false => 0,
  :error => 1,
  :COMMA => 2,
  :S => 3,
  :name => 4,
  "." => 5 }

racc_nt_base = 6

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "COMMA",
  "S",
  "name",
  "\".\"",
  "$start",
  "start",
  "selectors_group",
  "selector",
  "simple_selector_sequence",
  "annoying_bit",
  "combinator",
  "element_name",
  "modifier",
  "class" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

module_eval(<<'.,.,', 'css.racc', 7)
  def _reduce_2(val, _values, result)
     result = [:selectors_group, *val] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 8)
  def _reduce_3(val, _values, result)
     result = [:selectors_group, *val] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 9)
  def _reduce_4(val, _values, result)
     result = [:selectors_group, *val] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 12)
  def _reduce_5(val, _values, result)
     result = [:selector, *val] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 13)
  def _reduce_6(val, _values, result)
    first, *rest = *val; rest.flatten!(1); result =  [:selector, first, *rest] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 16)
  def _reduce_7(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 17)
  def _reduce_8(val, _values, result)
     previous_combinators = val.shift; result = previous_combinators + val 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 20)
  def _reduce_9(val, _values, result)
     result = [:simple_selector_sequence, *val] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 21)
  def _reduce_10(val, _values, result)
     first, *rest = *val; rest.flatten(1); result = [:simple_selector_sequence, first, *rest ]  
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 22)
  def _reduce_11(val, _values, result)
     first, *rest = *val; rest.flatten(1); result = [:simple_selector_sequence, first, *rest ]  
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 25)
  def _reduce_12(val, _values, result)
     result = [:element_name, *val] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 28)
  def _reduce_13(val, _values, result)
     result = [:class, val.flatten(1)] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 31)
  def _reduce_14(val, _values, result)
    result = [:name, val.last] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 34)
  def _reduce_15(val, _values, result)
     result = [:combinator, *val] 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Css
