#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.9
# from Racc grammer file "".
#

require 'racc/parser.rb'
module Css
  class Parser < Racc::Parser

module_eval(<<'...end css.racc/module_eval...', 'css.racc', 27)

def parse tokens
  @tokens = tokens
  do_parse
end

def next_token
  @tokens.shift
end
...end css.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
    12,     6,    11,     8,    10,     7,     6,     6,     6 ]

racc_action_check = [
     8,     8,     7,     3,     4,     1,     0,     9,    12 ]

racc_action_pointer = [
     2,     5,   nil,     1,     1,   nil,   nil,     2,    -3,     3,
   nil,   nil,     4,   nil,   nil,   nil ]

racc_action_default = [
   -10,   -10,    -1,    -2,    -5,    -7,    -8,   -10,   -10,   -10,
    -9,    16,   -10,    -4,    -6,    -3 ]

racc_goto_table = [
     2,    14,     1,     9,   nil,   nil,   nil,   nil,    13,   nil,
   nil,   nil,    15 ]

racc_goto_check = [
     2,     3,     1,     5,   nil,   nil,   nil,   nil,     2,   nil,
   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,     2,     0,    -8,   nil,    -1,   nil ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,   nil,     5 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 6, :_reduce_none,
  1, 7, :_reduce_2,
  4, 7, :_reduce_3,
  3, 7, :_reduce_4,
  1, 8, :_reduce_5,
  3, 8, :_reduce_6,
  1, 9, :_reduce_7,
  1, 11, :_reduce_8,
  1, 10, :_reduce_9 ]

racc_reduce_n = 10

racc_shift_n = 16

racc_token_table = {
  false => 0,
  :error => 1,
  :COMMA => 2,
  :S => 3,
  :name => 4 }

racc_nt_base = 5

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "COMMA",
  "S",
  "name",
  "$start",
  "start",
  "selectors_group",
  "selector",
  "simple_selector_sequence",
  "combinator",
  "element_name" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

module_eval(<<'.,.,', 'css.racc', 7)
  def _reduce_2(val, _values, result)
     result = [:selectors_group, *val] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 8)
  def _reduce_3(val, _values, result)
     result = [:selectors_group, *val] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 9)
  def _reduce_4(val, _values, result)
     result = [:selectors_group, *val] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 12)
  def _reduce_5(val, _values, result)
     result = [:selector, *val] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 13)
  def _reduce_6(val, _values, result)
    result =  [:selector, *val] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 16)
  def _reduce_7(val, _values, result)
     result = [:simple_selector_sequence, *val] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 19)
  def _reduce_8(val, _values, result)
     result = [:element_name, *val] 
    result
  end
.,.,

module_eval(<<'.,.,', 'css.racc', 22)
  def _reduce_9(val, _values, result)
     result = [:combinator, *val] 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Css
